name: PR Validation

on:
  pull_request:
    branches: [main, develop]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Build and test
        run: |
          ./scripts/build-all.sh
          ./scripts/test-all.sh
      
      - name: Code quality check
        run: echo "Run code quality checks"