name: Trigger DevOps Pipeline

on:
  push:
    branches: [dev, staging, main]
  pull_request:
    branches: [dev, staging, main]

jobs:
  trigger-devops:
    runs-on: ubuntu-latest
    steps:
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.DEVOPS_REPO_TOKEN }}
        repository: AmaliTech-Training-Academy/gep_devops
        event-type: backend-deployment
        client-payload: |
          {
            "ref": "${{ github.ref }}",
            "sha": "${{ github.sha }}",
            "repository": "${{ github.repository }}",
            "actor": "${{ github.actor }}",
            "event_name": "${{ github.event_name }}",
            "branch": "${{ github.ref_name }}",
            "environment": "${{ github.ref_name == 'prod' && 'prod' || github.ref_name == 'staging' && 'staging' || 'dev' }}"
          }
